# Site settings
title: Daniel Stone
subtitle: 16 year old student
email: contact@daniel-stone.uk
description: "A little about me."
url: "http://daniel-stone.uk" # the base hostname & protocol for your site
author: "Daniel Stone"

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/daniel-stoneuk
googleplus_url: https://plus.google.com/u/0/+DanielStone3
instagram_url: https://instagram.com/dan.stoney
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/daniel_stoneuk

# Build settings
markdown: kramdown

sass:
  style: compressed
